# -*- coding: utf-8 -*-
from . import RU10Helper, bin2Quaternary, helper, helper_cpu_single_core, quaternary2Bin
from .helper import (
    backend_calc_crc,
    base_str_to_int,
    bitSet,
    bitsSet,
    buildGraySequence,
    calc_file_crc,
    cluster_and_remove_index,
    crc_algo_from_str,
    fasta_cluster_and_remove_index,
    find_ceil_power_of_four,
    grayCode,
    listXOR,
    logical_xor,
    merge_folder_content,
    merge_parts,
    number_to_base_str,
    should_drop_packet,
    split_file,
    split_first,
    xor_mask,
    xor_numpy,
    xor_pakets,
    xor_with_seed,
)
from .RU10Helper import (
    choose_packet_numbers,
    from_true_false_list,
    intermediate_symbols,
    r_int63,
    ru10_triple_generator,
    systematic_ru10_triple_generator,
)

__all__ = [
    "RU10Helper",
    "bin2Quaternary",
    "helper",
    "helper_cpu_single_core",
    "quaternary2Bin",
    "base_str_to_int",
    "bitSet",
    "bitsSet",
    "buildGraySequence",
    "calc_crc",
    "calc_file_crc",
    "choose_packet_numbers",
    "cluster_and_remove_index",
    "crc_algo_from_str",
    "fasta_cluster_and_remove_index",
    "find_ceil_power_of_four",
    "from_true_false_list",
    "grayCode",
    "intermediate_symbols",
    "listXOR",
    "logical_xor",
    "merge_folder_content",
    "merge_parts",
    "number_to_base_str",
    "r_int63",
    "ru10_triple_generator",
    "should_drop_packet",
    "split_file",
    "split_first",
    "systematic_ru10_triple_generator",
    "xor_mask",
    "xor_numpy",
    "xor_pakets",
    "xor_with_seed",
]

calc_crc = backend_calc_crc
